name: Build and Deploy to gh-pages
on:
  push:
  pull_request:
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install drawio
        run: |
          sudo apt -y install wget curl
          curl -s https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | grep browser_download_url | grep '\.deb' | cut -d '"' -f 4 | wget -i -
          sudo apt -f install ./drawio-amd64-*.deb
      
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: open-machine-learning-jupyter-book
        environment-file: ./open-machine-learning-jupyter-book/environment.yml
        python-version: '3.9'
        auto-activate-base: false
        auto-update-conda: true

      - shell: bash -l {0}
      run: |
        conda info
      
      # Build the book
      - name: Build the book
        run: |
          cd algo-view
          jupyter-book clean -a .
          jupyter-book build --all -W --keep-going . 

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "algo-view/_build/html"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./algo-view/_build/html