name: Build and Deploy to Netlify
on:
  push:
    branches:
    - main
    # paths:
    # - algo-view/**

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install drawio
        run: |
          sudo apt -y install wget curl
          curl -s https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | grep browser_download_url | grep '\.deb' | cut -d '"' -f 4 | wget -i -
          sudo apt -f install ./drawio-amd64-*.deb
      
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: open-machine-learning-jupyter-book
        environment-file: ./open-machine-learning-jupyter-book/environment.yml
        python-version: '3.9'
        auto-activate-base: false
        auto-update-conda: true

      - shell: bash -l {0}
      run: |
        conda info
      
      # Build the book
      - name: Build the book
        run: |
          cd algo-view
          jupyter-book clean -a .
          jupyter-book build --all -W --keep-going . 

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "algo-view/_build/html"

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: 'algo-view/_build/html'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
